server:
 certFile: /opt/rdpgw/server.pem
 keyFile: /opt/rdpgw/key.pem
 gatewayAddress: localhost:9443
 port: 9443
 hosts:
  - xrdp:3389
 roundRobin: false
 sessionKey: thisisasessionkeyreplacethisjetz
 sessionEncryptionKey: thisisasessionkeyreplacethisnunu
client:
 usernameTemplate: "{{ username }}"
 networkAutoDetect: 0
 bandwidthAutoDetect: 1
 ConnectionType: 6
